---
kind: pipeline
type: docker
name: k8s-cluster

steps:
      
- name: initialize aws plugin for terraform
  image: rodrygocarnevali/ubu-tf-ansible:latest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret
  commands:
  - terraform init
  
- name: create aws infra
  image: rodrygocarnevali/ubu-tf-ansible:latest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret
  commands:
  - terraform apply -auto-approve
  
- name: apply ansible playbook
  image: rodrygocarnevali/ubu-tf-ansible:latest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret
    PRIVATE_KEY:
      from_secret: private_key
  commands:
  - mkdir -p ~/.ssh/
  - echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
  - unset PRIVATE_KEY
  - chmod 600 ~/.ssh/id_rsa
  - ansible-playbook -i inventory-plugin.py --limit "tag_name_tag-k8s" -u ubuntu --ssh-common-args='-o StrictHostKeyChecking=no' --private-key ~/.ssh/id_rsa playbook.yml

  

